### ISSUE TITLE
Save manually added IP with the IP list

### ISSUE THREAD

**Issue by lagnajeet** [Photonsters/Universal-Photon-Network-Controller#12]
When the user adds IP manually they should be saved so that they don't get overwritten by search function. It might be wise to add a setting where users can add IPs and the program remembers them between runs

**Comment by MakerMatrix** [comment]
This was my feature request haha.

It seems like when you search and find printers via the new broadcast function, they get cached 
 in the dropdown (where though?  I couldn't find where that is actually stored).  But before I successfully found them by broadcast, they weren't cached.

**Comment by lagnajeet** [comment]
I need to add this feature to cache manually added IPs. The settings are stored in the user configuration folder. I use the wxWigets function [_GetUserConfigDir_ ](https://docs.wxwidgets.org/3.0/classwx_standard_paths.html#a7c7cf595d94d29147360d031647476b0)to get the path where it is stored in a file named _settings.ini_ inside a folder named _PhotonTool_. Please follow the link to have a look at the documentation. It tells you where the user config folder is located based on the operating system.

**Comment by lagnajeet** [comment]
Now users can add save list of static IPs in the settings dialog
![image](https://user-images.githubusercontent.com/8535629/63673465-253a1d00-c799-11e9-9788-a017c4068103.png)
